# Generated by Django 2.1.2 on 2018-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_secondery_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='org',
            field=models.CharField(blank=True, max_length=120, verbose_name='Организация'),
        ),
    ]
