# Generated by Django 2.1.5 on 2019-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_registry_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_code',
            field=models.CharField(blank=True, default='НЕ УКАЗАН', max_length=30, verbose_name='Код ссылки'),
        ),
        migrations.AddField(
            model_name='document',
            name='url_code',
            field=models.CharField(blank=True, default='НЕ УКАЗАН', max_length=30, verbose_name='Код ссылки'),
        ),
        migrations.AddField(
            model_name='post',
            name='url_code',
            field=models.CharField(blank=True, default='НЕ УКАЗАН', max_length=30, verbose_name='Код ссылки'),
        ),
    ]
