# Generated by Django 2.1.5 on 2019-04-24 07:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190424_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidePanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
            ],
            options={
                'verbose_name_plural': 'Боковые панели',
                'verbose_name': 'Боковая панель',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='side_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.SidePanel', verbose_name='Боковая панель'),
        ),
    ]
