# Generated by Django 2.1.5 on 2019-04-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190424_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Категории документов',
                'verbose_name': 'Категория документа',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='cahegory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.DocumentCategory', verbose_name='Категория документа'),
        ),
    ]
