# Generated by Django 2.1.5 on 2019-04-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190424_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
