# Generated by Django 2.1.5 on 2019-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='number',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название категории'),
        ),
    ]
