# Generated by Django 2.1.5 on 2019-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190424_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='service_description',
            field=models.BooleanField(default=False, help_text='\n                    Когда выбрана эта опция автоматически будет создан пункт меню<br>\n                    в разделе "Услуги"\n    ', verbose_name='Описание услуги'),
        ),
    ]
