# Generated by Django 2.1.5 on 2019-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_post_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Код')),
                ('reg_number', models.CharField(blank=True, max_length=64, verbose_name='Регистрационный номер')),
                ('min_trud_register', models.CharField(blank=True, max_length=64, verbose_name='Приказ минтруда')),
                ('file', models.FileField(upload_to='upload/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Профессиональный стандарт',
                'verbose_name_plural': 'Профессиональные стандарты',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='service_description',
            field=models.BooleanField(default=False, help_text='\n                    Когда выбрана эта опция автоматически будет создан пункт меню<br>\n                    в разделе "Услуги". Код ссылки при этом можно не использовать.\n    ', verbose_name='Описание услуги'),
        ),
    ]
