# Generated by Django 2.1.5 on 2019-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='code',
            field=models.CharField(default='КОД_ВСТАВКИ', max_length=64, verbose_name='Уникальный код вставки'),
        ),
    ]
