# Generated by Django 2.1.5 on 2019-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_chunk_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profstandard',
            name='min_trud_register',
            field=models.CharField(blank=True, max_length=300, verbose_name='Приказ минтруда'),
        ),
    ]
