# Generated by Django 2.1.5 on 2019-04-25 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190425_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profstandard',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 8, 20, 20, 293618, tzinfo=utc)),
        ),
    ]
