# Generated by Django 2.1.5 on 2019-04-25 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_profstandard_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='profstandard',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 11, 10, 10, 420378, tzinfo=utc)),
        ),
    ]
