# Generated by Django 2.1.5 on 2019-04-25 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190425_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profstandard',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
