# Generated by Django 2.1.5 on 2019-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190425_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profstandard',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название'),
        ),
    ]
